default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 12345678

development:
  <<: *default
  database: linktreeclone_development

test:
  <<: *default
  database: linktreeclone_test

production:
  <<: *default
  database: linktreeclone_production
  username: linktreeclone
  password: <%= ENV["LINKTREECLONE_DATABASE_PASSWORD"] %>
